// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqDCD9aSPQBSN4RIhAdhWAZ9XFLeuee0',
    appId: '1:596683133951:web:1430c6e5bcb28bb5a6cdca',
    messagingSenderId: '596683133951',
    projectId: 'neuraltale-mali-up',
    authDomain: 'neuraltale-mali-up.firebaseapp.com',
    storageBucket: 'neuraltale-mali-up.firebasestorage.app',
    measurementId: 'G-5CBLCJFHF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChtvxfDDal92MUPeDMMJAwCWRtrNNrXJI',
    appId: '1:596683133951:android:04cfb6886a833d03a6cdca',
    messagingSenderId: '596683133951',
    projectId: 'neuraltale-mali-up',
    storageBucket: 'neuraltale-mali-up.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8AhAjg7cGr-z1pGJWo8uQzjLEobB-8uQ',
    appId: '1:596683133951:ios:db8e960349534a6fa6cdca',
    messagingSenderId: '596683133951',
    projectId: 'neuraltale-mali-up',
    storageBucket: 'neuraltale-mali-up.firebasestorage.app',
    iosBundleId: 'com.neuraltale.maliup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8AhAjg7cGr-z1pGJWo8uQzjLEobB-8uQ',
    appId: '1:596683133951:ios:db8e960349534a6fa6cdca',
    messagingSenderId: '596683133951',
    projectId: 'neuraltale-mali-up',
    storageBucket: 'neuraltale-mali-up.firebasestorage.app',
    iosBundleId: 'com.neuraltale.maliup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXqDCD9aSPQBSN4RIhAdhWAZ9XFLeuee0',
    appId: '1:596683133951:web:3b39a8867730f304a6cdca',
    messagingSenderId: '596683133951',
    projectId: 'neuraltale-mali-up',
    authDomain: 'neuraltale-mali-up.firebaseapp.com',
    storageBucket: 'neuraltale-mali-up.firebasestorage.app',
    measurementId: 'G-JBBDSRNSK3',
  );
}
