import 'package:flutter/foundation.dart';
import '../domain/models/expense.dart';
import '../../../core/services/firestore_service.dart';

class ExpenseProvider extends ChangeNotifier {
  final FirestoreService _firestoreService;
  List<Expense> _expenses = [];
  bool _isLoading = false;
  String? _error;

  // Expense categories
  static const List<String> expenseCategories = [
    'Food & Drinks',
    'Transport',
    'Rent',
    'Utilities',
    'Supplies',
    'Marketing',
    'Salaries',
    'Office',
    'Equipment',
    'Maintenance',
    'Insurance',
    'Taxes',
    'Other',
  ];

  ExpenseProvider({FirestoreService? firestoreService})
      : _firestoreService = firestoreService ?? FirestoreService();

  // Getters
  List<Expense> get expenses => List.unmodifiable(_expenses);
  bool get isLoading => _isLoading;
  String? get error => _error;
  bool get hasError => _error != null;
  int get expenseCount => _expenses.length;
  List<String> get categories => List.unmodifiable(expenseCategories);

  // Fetch expenses
  Future<void> fetchExpenses() async {
    _setLoading(true);
    try {
      final expenses = await _firestoreService.getExpenses();
      _expenses = expenses;
      _clearError();
    } catch (e) {
      _setError('Failed to fetch expenses: ${e.toString()}');
    } finally {
      _setLoading(false);
    }
  }

  // Add expense
  Future<bool> addExpense({
    required String category,
    required double amount,
    required String note,
    String recipient = '',
    String date = '',
  }) async {
    _setLoading(true);
    try {
      final expense = Expense(
        id: '', // Will be generated by Firestore
        category: category,
        amount: amount.toString(),
        date: date.isNotEmpty ? date : DateTime.now().toIso8601String().split('T')[0],
        note: note,
        recipient: recipient,
      );

      await _firestoreService.addExpense(expense);
      
      // Refresh the list
      await fetchExpenses();
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to add expense: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Update expense
  Future<bool> updateExpense(Expense expense) async {
    _setLoading(true);
    try {
      await _firestoreService.updateExpense(expense);
      
      // Update local list
      final index = _expenses.indexWhere((e) => e.id == expense.id);
      if (index != -1) {
        _expenses[index] = expense;
        notifyListeners();
      }
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to update expense: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Delete expense
  Future<bool> deleteExpense(String expenseId) async {
    _setLoading(true);
    try {
      await _firestoreService.deleteExpense(expenseId);
      
      // Remove from local list
      _expenses.removeWhere((e) => e.id == expenseId);
      notifyListeners();
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to delete expense: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Get expense by ID
  Expense? getExpenseById(String expenseId) {
    try {
      return _expenses.firstWhere((e) => e.id == expenseId);
    } catch (e) {
      return null;
    }
  }

  // Get expenses by category
  List<Expense> getExpensesByCategory(String category) {
    return _expenses.where((expense) => expense.category == category).toList();
  }

  // Get expenses by date range
  List<Expense> getExpensesByDateRange(DateTime startDate, DateTime endDate) {
    return _expenses.where((expense) {
      try {
        final expenseDate = DateTime.parse(expense.date);
        return expenseDate.isAfter(startDate.subtract(const Duration(days: 1))) &&
               expenseDate.isBefore(endDate.add(const Duration(days: 1)));
      } catch (e) {
        return false;
      }
    }).toList();
  }

  // Get today's expenses
  List<Expense> getTodayExpenses() {
    final today = DateTime.now();
    final todayString = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';
    
    return _expenses.where((expense) => expense.date == todayString).toList();
  }

  // Get month expenses
  List<Expense> getMonthExpenses() {
    final now = DateTime.now();
    final startOfMonth = DateTime(now.year, now.month, 1);
    final endOfMonth = DateTime(now.year, now.month + 1, 0);
    
    return getExpensesByDateRange(startOfMonth, endOfMonth);
  }

  // Get total expenses for today
  double getTodayTotal() {
    return getTodayExpenses()
        .fold<double>(0, (sum, expense) => sum + (double.tryParse(expense.amount) ?? 0));
  }

  // Get total expenses for month
  double getMonthTotal() {
    return getMonthExpenses()
        .fold<double>(0, (sum, expense) => sum + (double.tryParse(expense.amount) ?? 0));
  }

  // Get total expenses by category
  Map<String, double> getExpensesByCategoryTotal() {
    final Map<String, double> categoryTotals = {};
    
    for (final expense in _expenses) {
      final amount = double.tryParse(expense.amount) ?? 0;
      categoryTotals[expense.category] = (categoryTotals[expense.category] ?? 0) + amount;
    }
    
    return categoryTotals;
  }

  // Get expenses by category for current month
  Map<String, double> getMonthExpensesByCategory() {
    final monthExpenses = getMonthExpenses();
    final Map<String, double> categoryTotals = {};
    
    for (final expense in monthExpenses) {
      final amount = double.tryParse(expense.amount) ?? 0;
      categoryTotals[expense.category] = (categoryTotals[expense.category] ?? 0) + amount;
    }
    
    return categoryTotals;
  }

  // Get top expense categories
  List<MapEntry<String, double>> getTopExpenseCategories({int limit = 5}) {
    final categoryTotals = getMonthExpensesByCategory();
    final sortedEntries = categoryTotals.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    
    return sortedEntries.take(limit).toList();
  }

  // Search expenses
  List<Expense> searchExpenses(String query) {
    if (query.isEmpty) return _expenses;
    
    final lowerQuery = query.toLowerCase();
    return _expenses.where((expense) =>
      expense.category.toLowerCase().contains(lowerQuery) ||
      expense.note.toLowerCase().contains(lowerQuery) ||
      expense.recipient.toLowerCase().contains(lowerQuery) ||
      expense.amount.contains(query)
    ).toList();
  }

  // Get expense trends (last 7 days)
  Map<String, double> getWeeklyExpenseTrends() {
    final Map<String, double> dailyTotals = {};
    final now = DateTime.now();
    
    for (int i = 6; i >= 0; i--) {
      final date = now.subtract(Duration(days: i));
      final dateString = '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
      dailyTotals[dateString] = 0;
    }
    
    for (final expense in _expenses) {
      if (dailyTotals.containsKey(expense.date)) {
        final amount = double.tryParse(expense.amount) ?? 0;
        dailyTotals[expense.date] = (dailyTotals[expense.date] ?? 0) + amount;
      }
    }
    
    return dailyTotals;
  }

  // Refresh data
  Future<void> refresh() async {
    await fetchExpenses();
  }

  // Clear error
  void clearError() {
    _clearError();
  }

  // Private methods
  void _setLoading(bool loading) {
    if (_isLoading != loading) {
      _isLoading = loading;
      notifyListeners();
    }
  }

  void _setError(String error) {
    _error = error;
    notifyListeners();
  }

  void _clearError() {
    if (_error != null) {
      _error = null;
      notifyListeners();
    }
  }
}
