import 'package:flutter/foundation.dart';
import '../domain/models/invoice.dart';
import '../../../core/services/firestore_service.dart';

class InvoiceProvider extends ChangeNotifier {
  final FirestoreService _firestoreService;
  List<Invoice> _invoices = [];
  bool _isLoading = false;
  String? _error;

  InvoiceProvider({FirestoreService? firestoreService})
      : _firestoreService = firestoreService ?? FirestoreService();

  // Getters
  List<Invoice> get invoices => List.unmodifiable(_invoices);
  bool get isLoading => _isLoading;
  String? get error => _error;
  bool get hasError => _error != null;
  int get invoiceCount => _invoices.length;

  // Fetch invoices
  Future<void> fetchInvoices() async {
    _setLoading(true);
    try {
      final invoices = await _firestoreService.getInvoices();
      _invoices = invoices;
      _clearError();
    } catch (e) {
      _setError('Failed to fetch invoices: ${e.toString()}');
    } finally {
      _setLoading(false);
    }
  }

  // Add invoice
  Future<bool> addInvoice({
    required String customerId,
    required String customerName,
    required List<InvoiceItem> items,
    String? invoiceNumber,
    String? dueDate,
    String note = '',
    double taxRate = 0.18, // 18% VAT
  }) async {
    _setLoading(true);
    try {
      // Calculate totals
      final subtotal = items.fold<double>(0, (sum, item) => sum + item.total);
      final tax = subtotal * taxRate;
      final total = subtotal + tax;

      final invoice = Invoice(
        id: '', // Will be generated by Firestore
        customerId: customerId,
        customerName: customerName,
        invoiceNumber: invoiceNumber ?? _generateInvoiceNumber(),
        date: DateTime.now().toIso8601String().split('T')[0],
        dueDate: dueDate ?? DateTime.now().add(const Duration(days: 30)).toIso8601String().split('T')[0],
        status: 'pending',
        subtotal: subtotal,
        tax: tax,
        total: total,
        items: items,
        note: note,
        createdAt: DateTime.now().toIso8601String(),
        updatedAt: DateTime.now().toIso8601String(),
      );

      await _firestoreService.addInvoice(invoice);
      
      // Refresh the list
      await fetchInvoices();
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to add invoice: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Update invoice
  Future<bool> updateInvoice(Invoice invoice) async {
    _setLoading(true);
    try {
      await _firestoreService.updateInvoice(invoice);
      
      // Update local list
      final index = _invoices.indexWhere((i) => i.id == invoice.id);
      if (index != -1) {
        _invoices[index] = invoice;
        notifyListeners();
      }
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to update invoice: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Mark invoice as paid
  Future<bool> markAsPaid(String invoiceId) async {
    try {
      final invoice = _invoices.firstWhere((i) => i.id == invoiceId);
      final updatedInvoice = invoice.copyWith(
        status: 'paid',
        updatedAt: DateTime.now().toIso8601String(),
      );
      
      return await updateInvoice(updatedInvoice);
    } catch (e) {
      _setError('Failed to mark invoice as paid: ${e.toString()}');
      return false;
    }
  }

  // Delete invoice
  Future<bool> deleteInvoice(String invoiceId) async {
    _setLoading(true);
    try {
      await _firestoreService.deleteInvoice(invoiceId);
      
      // Remove from local list
      _invoices.removeWhere((i) => i.id == invoiceId);
      notifyListeners();
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to delete invoice: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Get invoice by ID
  Invoice? getInvoiceById(String invoiceId) {
    try {
      return _invoices.firstWhere((i) => i.id == invoiceId);
    } catch (e) {
      return null;
    }
  }

  // Get invoices by customer
  List<Invoice> getInvoicesByCustomer(String customerId) {
    return _invoices.where((invoice) => invoice.customerId == customerId).toList();
  }

  // Get invoices by status
  List<Invoice> getInvoicesByStatus(String status) {
    return _invoices.where((invoice) => invoice.status == status).toList();
  }

  // Get pending invoices
  List<Invoice> getPendingInvoices() {
    return getInvoicesByStatus('pending');
  }

  // Get paid invoices
  List<Invoice> getPaidInvoices() {
    return getInvoicesByStatus('paid');
  }

  // Get overdue invoices
  List<Invoice> getOverdueInvoices() {
    final now = DateTime.now();
    return _invoices.where((invoice) {
      if (invoice.status == 'paid') return false;
      try {
        final dueDate = DateTime.parse(invoice.dueDate);
        return dueDate.isBefore(now);
      } catch (e) {
        return false;
      }
    }).toList();
  }

  // Get today's sales
  double getTodaySales() {
    final today = DateTime.now();
    final todayString = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';
    
    return _invoices
        .where((invoice) => 
            invoice.date == todayString && 
            (invoice.status == 'paid' || invoice.status == 'pending'))
        .fold<double>(0, (sum, invoice) => sum + invoice.total);
  }

  // Get month sales
  double getMonthSales() {
    final now = DateTime.now();
    final startOfMonth = DateTime(now.year, now.month);
    final endOfMonth = DateTime(now.year, now.month + 1, 0);
    
    return _invoices
        .where((invoice) {
          try {
            final invoiceDate = DateTime.parse(invoice.date);
            return invoiceDate.isAfter(startOfMonth.subtract(const Duration(days: 1))) &&
                   invoiceDate.isBefore(endOfMonth.add(const Duration(days: 1))) &&
                   (invoice.status == 'paid' || invoice.status == 'pending');
          } catch (e) {
            return false;
          }
        })
        .fold<double>(0, (sum, invoice) => sum + invoice.total);
  }

  // Get total outstanding amount
  double getTotalOutstanding() {
    return _invoices
        .where((invoice) => invoice.status == 'pending')
        .fold<double>(0, (sum, invoice) => sum + invoice.total);
  }

  // Search invoices
  List<Invoice> searchInvoices(String query) {
    if (query.isEmpty) return _invoices;
    
    final lowerQuery = query.toLowerCase();
    return _invoices.where((invoice) =>
      invoice.customerName.toLowerCase().contains(lowerQuery) ||
      invoice.invoiceNumber.toLowerCase().contains(lowerQuery) ||
      invoice.status.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  // Generate WhatsApp receipt text
  String generateWhatsAppReceipt(String invoiceId) {
    final invoice = getInvoiceById(invoiceId);
    if (invoice == null) return '';

    final buffer = StringBuffer();
    buffer.writeln('🧾 *INVOICE*');
    buffer.writeln();
    buffer.writeln('**Invoice Number:** ${invoice.invoiceNumber}');
    buffer.writeln('**Customer:** ${invoice.customerName}');
    buffer.writeln('**Date:** ${invoice.date}');
    buffer.writeln('**Due Date:** ${invoice.dueDate}');
    buffer.writeln('**Status:** ${invoice.status.toUpperCase()}');
    buffer.writeln();
    buffer.writeln('**ITEMS:**');
    
    for (int i = 0; i < invoice.items.length; i++) {
      final item = invoice.items[i];
      buffer.writeln('${i + 1}. ${item.name}');
      buffer.writeln('   Qty: ${item.quantity} × ${item.unitPrice.toStringAsFixed(2)} = ${item.total.toStringAsFixed(2)}');
    }
    
    buffer.writeln();
    buffer.writeln('**SUBTOTAL:** ${invoice.subtotal.toStringAsFixed(2)}');
    buffer.writeln('**TAX (18%):** ${invoice.tax.toStringAsFixed(2)}');
    buffer.writeln('**TOTAL:** ${invoice.total.toStringAsFixed(2)}');
    
    if (invoice.note.isNotEmpty) {
      buffer.writeln();
      buffer.writeln('**Note:** ${invoice.note}');
    }
    
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln('Generated by Mali Up Business App');
    
    return buffer.toString();
  }

  // Generate invoice number
  String _generateInvoiceNumber() {
    final now = DateTime.now();
    const prefix = 'INV';
    final datePart = '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}';
    final randomPart = (1000 + (now.millisecondsSinceEpoch % 9000)).toString();
    return '$prefix-$datePart-$randomPart';
  }

  // Refresh data
  Future<void> refresh() async {
    await fetchInvoices();
  }

  // Clear error
  void clearError() {
    _clearError();
  }

  // Private methods
  void _setLoading(bool loading) {
    if (_isLoading != loading) {
      _isLoading = loading;
      notifyListeners();
    }
  }

  void _setError(String error) {
    _error = error;
    notifyListeners();
  }

  void _clearError() {
    if (_error != null) {
      _error = null;
      notifyListeners();
    }
  }
}
