import 'package:flutter/foundation.dart';
import '../domain/models/inventory_item.dart';
import '../../../core/services/firestore_service.dart';

class InventoryProvider extends ChangeNotifier {
  final FirestoreService _firestoreService;
  List<InventoryItem> _items = [];
  bool _isLoading = false;
  String? _error;

  // Inventory units
  static const List<String> inventoryUnits = [
    'pcs',
    'kg',
    'liters',
    'boxes',
    'bottles',
    'bags',
    'meters',
    'pairs',
    'sets',
    'dozens',
  ];

  // Inventory categories
  static const List<String> inventoryCategories = [
    'Electronics',
    'Clothing',
    'Food & Beverages',
    'Office Supplies',
    'Tools & Equipment',
    'Beauty & Personal Care',
    'Home & Garden',
    'Sports & Recreation',
    'Books & Media',
    'Toys & Games',
    'Health & Medical',
    'Automotive',
    'Other',
  ];

  InventoryProvider({FirestoreService? firestoreService})
      : _firestoreService = firestoreService ?? FirestoreService();

  // Getters
  List<InventoryItem> get items => List.unmodifiable(_items);
  bool get isLoading => _isLoading;
  String? get error => _error;
  bool get hasError => _error != null;
  int get itemCount => _items.length;
  List<String> get units => List.unmodifiable(inventoryUnits);
  List<String> get categories => List.unmodifiable(inventoryCategories);

  // Fetch inventory items
  Future<void> fetchInventoryItems() async {
    _setLoading(true);
    try {
      final items = await _firestoreService.getInventoryItems();
      _items = items;
      _clearError();
    } catch (e) {
      _setError('Failed to fetch inventory items: ${e.toString()}');
    } finally {
      _setLoading(false);
    }
  }

  // Add inventory item
  Future<bool> addInventoryItem({
    required String name,
    required String category,
    required double currentStock,
    required double reorderPoint,
    required double unitPrice,
    String unit = 'pcs',
    String description = '',
    String sku = '',
    String supplier = '',
  }) async {
    _setLoading(true);
    try {
      final item = InventoryItem(
        id: '', // Will be generated by Firestore
        name: name,
        description: description,
        category: category,
        sku: sku,
        currentStock: currentStock,
        reorderPoint: reorderPoint,
        unitPrice: unitPrice,
        unit: unit,
        supplier: supplier,
        lastRestocked: DateTime.now().toIso8601String(),
        createdAt: DateTime.now().toIso8601String(),
        updatedAt: DateTime.now().toIso8601String(),
      );

      await _firestoreService.addInventoryItem(item);
      
      // Refresh the list
      await fetchInventoryItems();
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to add inventory item: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Update inventory item
  Future<bool> updateInventoryItem(InventoryItem item) async {
    _setLoading(true);
    try {
      await _firestoreService.updateInventoryItem(item);
      
      // Update local list
      final index = _items.indexWhere((i) => i.id == item.id);
      if (index != -1) {
        _items[index] = item;
        notifyListeners();
      }
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to update inventory item: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Update stock quantity
  Future<bool> updateStock(String itemId, double newQuantity) async {
    try {
      final item = _items.firstWhere((i) => i.id == itemId);
      final updatedItem = item.copyWith(
        currentStock: newQuantity,
        lastRestocked: DateTime.now().toIso8601String(),
        updatedAt: DateTime.now().toIso8601String(),
      );
      
      return await updateInventoryItem(updatedItem);
    } catch (e) {
      _setError('Failed to update stock: ${e.toString()}');
      return false;
    }
  }

  // Add stock (restock)
  Future<bool> addStock(String itemId, double quantityToAdd) async {
    try {
      final item = _items.firstWhere((i) => i.id == itemId);
      final newQuantity = item.currentStock + quantityToAdd;
      
      return await updateStock(itemId, newQuantity);
    } catch (e) {
      _setError('Failed to add stock: ${e.toString()}');
      return false;
    }
  }

  // Remove stock (sale/usage)
  Future<bool> removeStock(String itemId, double quantityToRemove) async {
    try {
      final item = _items.firstWhere((i) => i.id == itemId);
      final newQuantity = (item.currentStock - quantityToRemove).clamp(0.0, double.infinity);
      
      return await updateStock(itemId, newQuantity);
    } catch (e) {
      _setError('Failed to remove stock: ${e.toString()}');
      return false;
    }
  }

  // Delete inventory item
  Future<bool> deleteInventoryItem(String itemId) async {
    _setLoading(true);
    try {
      await _firestoreService.deleteInventoryItem(itemId);
      
      // Remove from local list
      _items.removeWhere((i) => i.id == itemId);
      notifyListeners();
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to delete inventory item: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Get inventory item by ID
  InventoryItem? getItemById(String itemId) {
    try {
      return _items.firstWhere((i) => i.id == itemId);
    } catch (e) {
      return null;
    }
  }

  // Get items by category
  List<InventoryItem> getItemsByCategory(String category) {
    return _items.where((item) => item.category == category).toList();
  }

  // Get low stock items
  List<InventoryItem> getLowStockItems() {
    return _items.where((item) => item.isLowStock).toList();
  }

  // Get out of stock items
  List<InventoryItem> getOutOfStockItems() {
    return _items.where((item) => item.isOutOfStock).toList();
  }

  // Get in stock items
  List<InventoryItem> getInStockItems() {
    return _items.where((item) => !item.isOutOfStock).toList();
  }

  // Search inventory items
  List<InventoryItem> searchItems(String query) {
    if (query.isEmpty) return _items;
    
    final lowerQuery = query.toLowerCase();
    return _items.where((item) =>
      item.name.toLowerCase().contains(lowerQuery) ||
      item.description.toLowerCase().contains(lowerQuery) ||
      item.category.toLowerCase().contains(lowerQuery) ||
      item.sku.toLowerCase().contains(lowerQuery) ||
      item.supplier.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  // Get total inventory value
  double getTotalInventoryValue() {
    return _items.fold<double>(0, (sum, item) => sum + item.stockValue);
  }

  // Get total inventory value by category
  Map<String, double> getInventoryValueByCategory() {
    final Map<String, double> categoryValues = {};
    
    for (final item in _items) {
      categoryValues[item.category] = (categoryValues[item.category] ?? 0) + item.stockValue;
    }
    
    return categoryValues;
  }

  // Get low stock value (items that need restocking)
  double getLowStockValue() {
    return getLowStockItems()
        .fold<double>(0, (sum, item) => sum + item.stockValue);
  }

  // Get out of stock value
  double getOutOfStockValue() {
    return getOutOfStockItems()
        .fold<double>(0, (sum, item) => sum + item.reorderValue);
  }

  // Get stock statistics
  Map<String, dynamic> getStockStatistics() {
    final totalItems = _items.length;
    final inStockCount = getInStockItems().length;
    final lowStockCount = getLowStockItems().length;
    final outOfStockCount = getOutOfStockItems().length;
    
    return {
      'totalItems': totalItems,
      'inStockCount': inStockCount,
      'lowStockCount': lowStockCount,
      'outOfStockCount': outOfStockCount,
      'inStockPercentage': totalItems > 0 ? (inStockCount / totalItems * 100).roundToDouble() : 0,
      'lowStockPercentage': totalItems > 0 ? (lowStockCount / totalItems * 100).roundToDouble() : 0,
      'outOfStockPercentage': totalItems > 0 ? (outOfStockCount / totalItems * 100).roundToDouble() : 0,
      'totalValue': getTotalInventoryValue(),
      'lowStockValue': getLowStockValue(),
      'outOfStockValue': getOutOfStockValue(),
    };
  }

  // Get items that need restocking (below reorder point)
  List<InventoryItem> getItemsNeedingRestock() {
    return _items.where((item) => item.currentStock <= item.reorderPoint).toList();
  }

  // Generate restock suggestions
  List<Map<String, dynamic>> generateRestockSuggestions() {
    final itemsNeedingRestock = getItemsNeedingRestock();
    final suggestions = <Map<String, dynamic>>[];
    
    for (final item in itemsNeedingRestock) {
      final suggestedOrder = (item.reorderPoint * 2) - item.currentStock;
      suggestions.add({
        'item': item,
        'suggestedQuantity': suggestedOrder,
        'suggestedValue': suggestedOrder * item.unitPrice,
        'urgency': item.isOutOfStock ? 'high' : 'medium',
      });
    }
    
    // Sort by urgency and value
    suggestions.sort((a, b) {
      final urgencyComparison = a['urgency'].toString().compareTo(b['urgency'].toString());
      if (urgencyComparison != 0) return urgencyComparison;
      
      return (b['suggestedValue'] as double).compareTo(a['suggestedValue'] as double);
    });
    
    return suggestions;
  }

  // Refresh data
  Future<void> refresh() async {
    await fetchInventoryItems();
  }

  // Clear error
  void clearError() {
    _clearError();
  }

  // Private methods
  void _setLoading(bool loading) {
    if (_isLoading != loading) {
      _isLoading = loading;
      notifyListeners();
    }
  }

  void _setError(String error) {
    _error = error;
    notifyListeners();
  }

  void _clearError() {
    if (_error != null) {
      _error = null;
      notifyListeners();
    }
  }
}
