import 'package:flutter/foundation.dart';
import '../domain/models/customer.dart';
import '../../../core/services/firestore_service.dart';

class CustomerProvider extends ChangeNotifier {
  final FirestoreService _firestoreService;
  List<Customer> _customers = [];
  bool _isLoading = false;
  String? _error;

  CustomerProvider({FirestoreService? firestoreService})
      : _firestoreService = firestoreService ?? FirestoreService();

  // Getters
  List<Customer> get customers => List.unmodifiable(_customers);
  bool get isLoading => _isLoading;
  String? get error => _error;
  bool get hasError => _error != null;
  int get customerCount => _customers.length;

  // Fetch customers
  Future<void> fetchCustomers() async {
    _setLoading(true);
    try {
      final customers = await _firestoreService.getCustomers();
      _customers = customers;
      _clearError();
    } catch (e) {
      _setError('Failed to fetch customers: ${e.toString()}');
    } finally {
      _setLoading(false);
    }
  }

  // Add customer
  Future<bool> addCustomer({
    required String name,
    required String phone,
    String email = '',
    String balance = '0',
    String lastTransactionDate = '',
    List<String> tags = const [],
  }) async {
    _setLoading(true);
    try {
      final customer = Customer(
        id: '', // Will be generated by Firestore
        name: name,
        phone: phone,
        email: email,
        balance: balance,
        lastTransactionDate: lastTransactionDate,
        tags: tags,
      );

      final customerId = await _firestoreService.addCustomer(customer);
      
      // Refresh the list
      await fetchCustomers();
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to add customer: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Update customer
  Future<bool> updateCustomer(Customer customer) async {
    _setLoading(true);
    try {
      await _firestoreService.updateCustomer(customer);
      
      // Update local list
      final index = _customers.indexWhere((c) => c.id == customer.id);
      if (index != -1) {
        _customers[index] = customer;
        notifyListeners();
      }
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to update customer: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Delete customer
  Future<bool> deleteCustomer(String customerId) async {
    _setLoading(true);
    try {
      await _firestoreService.deleteCustomer(customerId);
      
      // Remove from local list
      _customers.removeWhere((c) => c.id == customerId);
      notifyListeners();
      
      _clearError();
      return true;
    } catch (e) {
      _setError('Failed to delete customer: ${e.toString()}');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  // Get customer by ID
  Customer? getCustomerById(String customerId) {
    try {
      return _customers.firstWhere((c) => c.id == customerId);
    } catch (e) {
      return null;
    }
  }

  // Search customers
  List<Customer> searchCustomers(String query) {
    if (query.isEmpty) return _customers;
    
    final lowerQuery = query.toLowerCase();
    return _customers.where((customer) =>
      customer.name.toLowerCase().contains(lowerQuery) ||
      customer.phone.toLowerCase().contains(lowerQuery) ||
      customer.email.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  // Get customers with outstanding balance
  List<Customer> getCustomersWithDebt() {
    return _customers.where((customer) {
      try {
        final balance = double.tryParse(customer.balance) ?? 0;
        return balance < 0; // Negative balance means they owe money
      } catch (e) {
        return false;
      }
    }).toList();
  }

  // Get total outstanding debt
  double getTotalOutstandingDebt() {
    double total = 0;
    for (final customer in getCustomersWithDebt()) {
      try {
        final balance = double.tryParse(customer.balance) ?? 0;
        total += balance.abs();
      } catch (e) {
        continue;
      }
    }
    return total;
  }

  // Refresh data
  Future<void> refresh() async {
    await fetchCustomers();
  }

  // Clear error
  void clearError() {
    _clearError();
  }

  // Private methods
  void _setLoading(bool loading) {
    if (_isLoading != loading) {
      _isLoading = loading;
      notifyListeners();
    }
  }

  void _setError(String error) {
    _error = error;
    notifyListeners();
  }

  void _clearError() {
    if (_error != null) {
      _error = null;
      notifyListeners();
    }
  }
}
