import type { Metadata } from 'next'
import { LegalPage, LegalSection } from '@/components/mali/legal-shell'

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://maliup.neuraltale.com'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'The terms and conditions that govern your use of Mali Up — eligibility, account responsibility, acceptable use, and Tanzania governing law.',
  alternates: { canonical: `${BASE_URL}/terms` },
}

export default function TermsOfServicePage() {
  return (
    <LegalPage title="Terms of Service" updated="May 24, 2026">
      <LegalSection title="1. Acceptance of Terms">
        <p>By creating an account or using Mali Up, you agree to be bound by these Terms of Service. If you do not agree, please do not use the app.</p>
      </LegalSection>

      <LegalSection title="2. What Mali Up Is">
        <p>
          Mali Up is a business record-keeping platform. We record and organise your financial
          transactions — we do not hold, transfer, or process funds, and we are not a payment
          institution or bank.
        </p>
      </LegalSection>

      <LegalSection title="3. Eligibility">
        <p>You must be 18 years or older and operate a legitimate business (or maintain a legitimate personal account) to use Mali Up.</p>
      </LegalSection>

      <LegalSection title="4. Account Responsibility">
        <p>
          You are responsible for keeping your PIN and login credentials secure. Mali Up is not
          liable for unauthorised access resulting from shared or compromised credentials.
        </p>
      </LegalSection>

      <LegalSection title="5. Acceptable Use">
        <p>Mali Up is for lawful business and personal record-keeping only. Fraudulent, illegal, or deceptive use of the app is strictly prohibited.</p>
      </LegalSection>

      <LegalSection title="6. Data Accuracy">
        <p>You are responsible for the accuracy of the data you enter. Reports and insights generated by Mali Up are based entirely on the data you provide.</p>
      </LegalSection>

      <LegalSection title="7. Service Availability">
        <p>We aim for 99.9% uptime but do not guarantee uninterrupted service. Planned maintenance will be communicated in advance where possible.</p>
      </LegalSection>

      <LegalSection title="8. Limitation of Liability">
        <p>Mali Up is not liable for financial decisions made based on data recorded in the app. The app is a record-keeping tool, not financial or legal advice.</p>
      </LegalSection>

      <LegalSection title="9. Termination">
        <p>You may delete your account and data at any time from Settings. We may suspend or terminate accounts that violate these Terms or applicable law.</p>
      </LegalSection>

      <LegalSection title="10. Governing Law">
        <p>These Terms are governed by the laws of the United Republic of Tanzania.</p>
      </LegalSection>

      <LegalSection title="11. Changes to These Terms">
        <p>We may update these Terms from time to time. Continued use of Mali Up after changes take effect constitutes acceptance of the revised Terms.</p>
      </LegalSection>

      <LegalSection title="12. Contact Us">
        <p>
          Questions about these Terms? Contact us at{' '}
          <a href="mailto:support@neuraltale.com" className="text-[#F5A623] hover:underline">
            support@neuraltale.com
          </a>
          .
        </p>
      </LegalSection>
    </LegalPage>
  )
}
